-- Create a schema and import a file

create database if not exists market;
use market;

create table data(

Campaign_ID	int primary key,
Company	varchar(100),
Campaign_Type varchar(100),
Target_Audience char(100),	
Duration int,
Channel_Used varchar(50),
Conversion_Rate	float,
Acquisition_Cost int,
ROI	float,
Location varchar(50),	
Language varchar(50),	
Clicks int,	
Impressions int,	
Engagement_Score int,	
Customer_Segment varchar(100),	
Date varchar(50)
);
select * from data;

load data infile
'C:/marketing_campaign_dataset.csv'
into table data fields terminated by ','
ignore 1 lines;

-- Average cost of company
select avg(Acquisition_Cost) from data;

-- Maximum Conversion Rate of Company
select Company, max(Conversion_Rate) from data 
group by Company;

-- Maximum ROI by company
select Company, max(ROI) from data 
group by Company;

-- Channel has max ROI
select Channel_Used, max(ROI) from data
group by Channel_used;

-- Total click generated by each channel
select Channel_Used, sum(Clicks) from data
group by Channel_Used;

-- Maximum click on day
select Date, max(Clicks) from data
group by date;

-- Total cost incurred by company
select company, sum(Acquisition_Cost) from data
group by company;

-- Avg, Max, Min Converion rate for Target Audience
select Target_Audience,
avg(Conversion_Rate),
max(Conversion_Rate),
min(Conversion_Rate) 
from data 
group by Target_Audience;


-- Avg, Max, Min Converion rate for Duration
select Duration,
avg(Conversion_Rate),
max(Conversion_Rate),
min(Conversion_Rate) 
from data 
group by Duration;

-- Total no of Clicks for each company
select Company, sum(Clicks) from data
group by Company;

-- No of clicks in each location and language
select Location, Language, sum(Clicks) from data
group by Location, Language;

-- Avg Engagement_Score in each month.
select Date, avg(Engagement_Score) from data
group by Date;

-- Total no of click for the interval of 15 days 
SELECT Customer_Segment, SUM(Clicks) FROM data where  Customer_Segment = 'Health & Wellness'
BETWEEN '2021-04-01' AND DATE_ADD('2021-04-01', INTERVAL 15 DAY);


